### ISSUE TITLE
AttributeError: 'MecabBertTokenizer' object has no attribute 'vocab'

### ISSUE THREAD

**Issue by shuxinjin** [cl-tohoku/bert-japanese#17]
Traceback (most recent call last):
  File "C:\Users\jsx\.p2\pool\plugins\org.python.pydev.core_7.7.0.202008021154\pysrc\pydevd.py", line 3206, in <module>
    main()
  File "C:\Users\jsx\.p2\pool\plugins\org.python.pydev.core_7.7.0.202008021154\pysrc\pydevd.py", line 3199, in main
    globals = debugger.run(setup['file'], None, None, is_module)
  File "C:\Users\jsx\.p2\pool\plugins\org.python.pydev.core_7.7.0.202008021154\pysrc\pydevd.py", line 2273, in run
    return self._exec(is_module, entry_point_fn, module_name, file, globals, locals)
  File "C:\Users\jsx\.p2\pool\plugins\org.python.pydev.core_7.7.0.202008021154\pysrc\pydevd.py", line 2280, in _exec
    pydev_imports.execfile(file, globals, locals)  # execute the script
  File "C:\Users\jsx\.p2\pool\plugins\org.python.pydev.core_7.7.0.202008021154\pysrc\_pydev_imps\_pydev_execfile.py", line 25, in execfile
    exec(compile(contents+"\n", file, 'exec'), glob, loc)
  File "D:\coding\NLP_AI\BERT\japanese_bert_1_0\masked_lm_main.py", line 32, in <module>
    tokenizer = MecabBertTokenizer(vocab_file=f'{BERT_BASE_DIR}/vocab.txt')
  File "D:\coding\NLP_AI\BERT\japanese_bert_1_0\tokenization.py", line 53, in __init__
    self.max_len_single_sentence = self.max_len - 2  # take into account special tokens
  File "C:\ProgramData\Anaconda3\lib\site-packages\transformers\tokenization_utils_base.py", line 1066, in max_len_single_sentence
    if value == self.model_max_length - self.num_special_tokens_to_add(pair=False) and self.verbose:
  File "C:\ProgramData\Anaconda3\lib\site-packages\transformers\tokenization_utils.py", line 254, in num_special_tokens_to_add
    return len(self.build_inputs_with_special_tokens(token_ids_0, token_ids_1 if pair else None))
  File "C:\ProgramData\Anaconda3\lib\site-packages\transformers\tokenization_bert.py", line 256, in build_inputs_with_special_tokens
    return [self.cls_token_id] + token_ids_0 + [self.sep_token_id]
  File "C:\ProgramData\Anaconda3\lib\site-packages\transformers\tokenization_utils_base.py", line 858, in cls_token_id
    return self.convert_tokens_to_ids(self.cls_token)
  File "C:\ProgramData\Anaconda3\lib\site-packages\transformers\tokenization_utils.py", line 384, in convert_tokens_to_ids
    return self._convert_token_to_id_with_added_voc(tokens)
  File "C:\ProgramData\Anaconda3\lib\site-packages\transformers\tokenization_utils.py", line 397, in _convert_token_to_id_with_added_voc
    return self._convert_token_to_id(token)
  File "C:\ProgramData\Anaconda3\lib\site-packages\transformers\tokenization_bert.py", line 224, in _convert_token_to_id
    return self.vocab.get(token, self.vocab.get(self.unk_token))
AttributeError: 'MecabBertTokenizer' object has no attribute 'vocab'

=============
(base) C:\Users\jsx>pip list
Package                            Version
---------------------------------- -------------------
absl-py                            0.9.0
alabaster                          0.7.12
amqp                               1.4.9
anaconda-client                    1.7.2
anaconda-navigator                 1.9.12
anaconda-project                   0.8.3
antiorm                            1.2.1
anyjson                            0.3.3
APScheduler                        3.6.3
argh                               0.26.2
arrow                              0.13.0
asari                              0.0.4
asgiref                            3.2.10
asn1crypto                         1.3.0
astroid                            2.4.2
astropy                            4.0.1.post1
astunparse                         1.6.3
atomicwrites                       1.4.0
attrs                              19.3.0
Automat                            20.2.0
autopep8                           1.5.3
Babel                              2.8.0
backcall                           0.2.0
backports.functools-lru-cache      1.6.1
backports.shutil-get-terminal-size 1.0.0
backports.tempfile                 1.0
backports.weakref                  1.0.post1
bcrypt                             3.1.7
beautifulsoup4                     4.9.1
billiard                           3.3.0.23
bitarray                           1.4.0
bkcharts                           0.2
bleach                             3.1.5
blis                               0.4.1
bokeh                              2.1.1
boto                               2.49.0
boto3                              1.14.35
botocore                           1.17.35
Bottleneck                         1.3.2
breadability                       0.1.20
brotlipy                           0.7.0
cachetools                         4.1.1
catalogue                          1.0.0
celery                             3.1.26.post2
certifi                            2020.6.20
cffi                               1.14.0
chardet                            3.0.4
click                              7.1.2
cloudpickle                        1.5.0
clyent                             1.2.2
colorama                           0.4.3
comtypes                           1.1.7
conda                              4.8.3
conda-build                        3.18.11
conda-package-handling             1.7.0
conda-verify                       3.4.2
constantly                         15.1.0
contextlib2                        0.6.0.post1
contextvars                        2.4
crispy-forms-gds                   0.2.1
cryptography                       2.9.2
cssselect                          1.1.0
cycler                             0.10.0
cymem                              2.0.3
Cython                             0.29.14
cytoolz                            0.10.1
dartsclone                         0.9.0
dask                               2.20.0
dataclasses                        0.7
db                                 0.1.1
db-sqlite3                         0.0.1
decorator                          4.4.2
defusedxml                         0.6.0
diff-match-patch                   20200713
dill                               0.2.9
distributed                        2.20.0
Django                             3.1
django-bootstrap3                  14.1.0
django-celery                      3.3.1
django-crispy-forms                1.9.2
django-crontab                     0.7.1
django-debug-toolbar               2.2
django-filter                      2.3.0
django-import-export               2.3.0
django-mathfilters                 1.0.0
django-paypal                      1.0.0
docker                             4.2.2
docopt                             0.6.2
docutils                           0.15.2
en-core-web-md                     2.2.5
en-core-web-sm                     2.2.5
entrypoints                        0.3
et-xmlfile                         1.0.1
fake-useragent                     0.1.11
fastcache                          1.1.0
filelock                           3.0.12
fix-yahoo-finance                  0.1.37
flake8                             3.8.3
Flask                              1.1.2
Flask-APScheduler                  1.11.0
Flask-SQLAlchemy                   2.4.4
Flask-WTF                          0.14.3
fsspec                             0.7.4
future                             0.18.2
gast                               0.3.3
gensim                             3.6.0
gensim-sum-ext                     0.1.2
gevent                             20.6.2
ginza                              3.1.2
glob2                              0.7
gmpy2                              2.0.8
google-auth                        1.20.0
google-auth-oauthlib               0.4.1
google-pasta                       0.2.0
greenlet                           0.4.16
grpcio                             1.31.0
h5py                               2.10.0
HeapDict                           1.0.1
helpdev                            0.7.1
html5lib                           1.1
hyperlink                          20.0.1
idna                               2.10
imageio                            2.9.0
imagesize                          1.2.0
immutables                         0.14
importlib-metadata                 1.7.0
incremental                        17.5.0
intervaltree                       3.0.2
ipykernel                          5.3.2
ipython                            7.16.1
ipython-genutils                   0.2.0
ipywidgets                         7.5.1
isort                              4.3.21
itsdangerous                       1.1.0
ja-ginza                           3.1.0
ja-ginza-dict                      3.1.0
Janome                             0.3.10
jdcal                              1.4.1
jedi                               0.17.1
Jinja2                             2.11.2
jmespath                           0.10.0
joblib                             0.16.0
json5                              0.9.5
jsonschema                         3.2.0
jupyter                            1.0.0
jupyter-client                     6.1.6
jupyter-console                    6.1.0
jupyter-core                       4.6.3
jupyterlab                         2.1.5
jupyterlab-server                  1.2.0
Keras                              2.4.3
Keras-Preprocessing                1.1.2
keyring                            21.2.1
kiwisolver                         1.2.0
kombu                              3.0.37
lazy-object-proxy                  1.4.3
libarchive-c                       2.9
llvmlite                           0.33.0+1.g022ab0f
locket                             0.2.0
lxml                               4.5.2
Markdown                           3.2.2
MarkupPy                           1.14
MarkupSafe                         1.1.1
matplotlib                         3.2.2
mccabe                             0.6.1
mecab                              0.996.2
mecab-python                       1.0.0
mecab-python3                      1.0.1
menuinst                           1.4.16
mistune                            0.8.4
mkl-fft                            1.0.14
mkl-random                         1.0.4
mkl-service                        2.3.0
mock                               4.0.2
more-itertools                     8.4.0
mpmath                             1.1.0
msgpack                            0.5.6
multipledispatch                   0.6.0
multitasking                       0.0.9
murmurhash                         1.0.2
mysql-connector                    2.2.9
mysqlclient                        2.0.1
navigator-updater                  0.2.1
nbconvert                          5.6.1
nbformat                           5.0.7
networkx                           2.4
nltk                               3.5
nose                               1.3.7
notebook                           6.0.3
numba                              0.50.1
numexpr                            2.7.1
numpy                              1.18.5
numpydoc                           1.1.0
oauthlib                           3.1.0
odfpy                              1.4.1
olefile                            0.46
openpyxl                           3.0.4
opt-einsum                         3.3.0
packaging                          20.4
pandas                             1.0.5
pandas-datareader                  0.9.0
pandocfilters                      1.4.2
paramiko                           2.7.1
parso                              0.7.0
partd                              1.1.0
path                               13.1.0
pathlib2                           2.3.5
pathtools                          0.1.2
patsy                              0.5.1
pep8                               1.7.1
pexpect                            4.8.0
pickleshare                        0.7.5
Pillow                             7.2.0
pip                                20.1.1
pkginfo                            1.5.0.1
plac                               0.9.6
pluggy                             0.13.1
ply                                3.11
preshed                            3.0.2
prometheus-client                  0.8.0
prompt-toolkit                     3.0.5
protobuf                           3.12.4
psutil                             5.7.0
ptyprocess                         0.6.0
py                                 1.9.0
pyasn1                             0.4.8
pyasn1-modules                     0.2.8
pycodestyle                        2.6.0
pycorenlp                          0.3.0
pycosat                            0.6.3
pycountry                          20.7.3
pycparser                          2.20
pycrypto                           2.6.1
pycurl                             7.43.0.5
pydocstyle                         5.0.2
pyflakes                           2.2.0
Pygments                           2.6.1
PyHamcrest                         2.0.2
pylint                             2.5.3
PyMySQL                            0.10.0
PyNaCl                             1.4.0
pyodbc                             4.0.0-unsupported
pyOpenSSL                          19.1.0
pyparsing                          2.4.7
pypiwin32                          223
PyQt5                              5.12.3
PyQt5-sip                          12.8.0
PyQtWebEngine                      5.12.1
pyquery                            1.4.1
pyreadline                         2.1
pyrsistent                         0.16.0
PySocks                            1.7.1
pystan                             2.19.1.1
pytest                             5.4.3
python-dateutil                    2.8.1
python-jsonrpc-server              0.3.4
python-language-server             0.34.1
pytz                               2020.1
PyWavelets                         1.1.1
pywin32                            227
pywin32-ctypes                     0.2.0
pywinpty                           0.5.7
PyYAML                             5.3.1
pyzmq                              19.0.2
QDarkStyle                         2.8.1
QtAwesome                          0.7.2
qtconsole                          4.7.5
QtPy                               1.9.0
redis                              3.2.1
regex                              2020.6.8
requests                           2.24.0
requests-oauthlib                  1.3.0
rope                               0.17.0
rsa                                4.6
Rtree                              0.9.4
ruamel-yaml                        0.15.87
s3transfer                         0.3.3
sacremoses                         0.0.43
scikit-image                       0.16.2
scikit-learn                       0.23.1
scipy                              1.4.1
seaborn                            0.10.1
Send2Trash                         1.5.0
sentencepiece                      0.1.91
setuptools                         49.2.0.post20200714
simplegeneric                      0.8.1
simplejson                         3.17.2
singledispatch                     3.4.0.3
six                                1.15.0
smart-open                         2.1.0
snowballstemmer                    2.0.0
sortedcollections                  1.2.1
sortedcontainers                   2.1.0
soupsieve                          2.0.1
spacy                              2.2.3
Sphinx                             3.1.2
sphinxcontrib-applehelp            1.0.2
sphinxcontrib-devhelp              1.0.2
sphinxcontrib-htmlhelp             1.0.3
sphinxcontrib-jsmath               1.0.1
sphinxcontrib-qthelp               1.0.3
sphinxcontrib-serializinghtml      1.1.4
sphinxcontrib-websupport           1.2.3
spyder                             4.1.4
spyder-kernels                     1.9.2
SQLAlchemy                         1.3.18
sqlparse                           0.3.1
srsly                              1.0.2
statsmodels                        0.11.1
SudachiDict-core                   20191030
SudachiPy                          0.4.5
sumy                               0.8.1
sympy                              1.6.1
tables                             3.6.1
tablib                             2.0.0
tblib                              1.6.0
tensorboard                        2.3.0
tensorboard-plugin-wit             1.7.0
tensorflow                         2.3.0
tensorflow-estimator               2.3.0
tensorflow-hub                     0.8.0
termcolor                          1.1.0
terminado                          0.8.3
testpath                           0.4.4
textblob                           0.15.3
thinc                              7.3.1
threadpoolctl                      2.1.0
tokenization                       1.0.7
tokenizers                         0.8.1rc1
toml                               0.10.1
toolz                              0.10.0
torch                              1.1.0
torchvision                        0.3.0
tornado                            6.0.4
tqdm                               4.47.0
traitlets                          4.3.3
transformers                       3.0.2
Twisted                            20.3.0
typed-ast                          1.4.1
typing-extensions                  3.7.4.2
tzlocal                            2.1
ujson                              1.35
unicodecsv                         0.14.1
unidic-lite                        1.0.7
urllib3                            1.25.9
vine                               1.3.0
wasabi                             0.7.1
watchdog                           0.10.3
wcwidth                            0.2.5
webencodings                       0.5.1
websocket-client                   0.57.0
Werkzeug                           1.0.1
wheel                              0.34.2
widgetsnbextension                 3.5.1
win-inet-pton                      1.1.0
win-unicode-console                0.5
wincertstore                       0.2
wrapt                              1.12.1
WTForms                            2.3.3
xlrd                               1.2.0
XlsxWriter                         1.2.9
xlwings                            0.19.5
xlwt                               1.3.0
xmltodict                          0.12.0
yahoo-finance                      1.4.0
YahooFinanceSpider                 0.3
yapf                               0.30.0
yfinance                           0.1.54
zict                               2.0.0
zipp                               3.1.0
zmq                                0.0.0
zope.event                         4.4
zope.interface                     4.7.1

**Comment by shuxinjin** [comment]
tokenizer = MecabBertTokenizer(vocab_file=f'{BERT_BASE_DIR}/vocab.txt')

**Comment by shuxinjin** [comment]
I resolved it by myself. It is a error in "tokenization.py".The latest version even not correct it.

**Comment by firenhan1** [comment]
How can you resolve it, @shuxinjin? Please help me. 
I am facing the same problem.


AttributeError: 'MecabCharacterBertTokenizer' object has no attribute 'vocab'

**Comment by a1da4** [comment]
@firenhan1 
May be in "tokenization.py", these 2 lines [L53-54](https://github.com/cl-tohoku/bert-japanese/blob/master/tokenization.py#L53:L54) refer "self.vocab" before it is defined in [L60](https://github.com/cl-tohoku/bert-japanese/blob/master/tokenization.py#L60).

**Comment by singletongue** [comment]
Sorry for the late response.
If it is still unresolved, try initializing tokenizers from `transformers` package, not from `tokenization.py` in our repository.
(Our `tokenization.py` had not been updated along with the recent versions of `transformers`.)

**Comment by shuxinjin** [comment]
> How can you resolve it, @shuxinjin? Please help me.
> I am facing the same problem.
> 
> AttributeError: 'MecabCharacterBertTokenizer' object has no attribute 'vocab'

==below is my resolve method==

tokenization.py,
#Line 189 should be corrected to
token, token_info , *rest= line.split('\t')
